spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: dudgus94
    driver-class-name: com.mysql.cj.jdbc.Driver

